#! /usr/bin/python

"""
choose x0, y0 with left mouse button while pressing 'a'
choose x1, y1 with left mouse button while pressing 's'
choose data points with left mouse button while pressing 'd'
"""

import sys
import matplotlib
matplotlib.use('TkAgg')
from pylab import *
from matplotlib import widgets

ax = None
i0 = None
outf = None
xlog = 0
ylog = 0
def plotimage():
    global cursor
    from PIL import Image
    fn = inp[0].get()
    fn = fn.strip()
    print('Reading Infile: %s'%fn)
    d = Image.open(fn)
    d = d.transpose(Image.FLIP_TOP_BOTTOM)
    try:
        clf()
    except:
        pass
    subplot(1,1,1)
    subplots_adjust(left=0, right=1, bottom=0, top=1)
    a = imshow(d, origin='lower')
    a = gca()
    cursor = widgets.Cursor(a, color='red', linewidth=1.1)
    axis('off')
    show()
    try:
        qid = connect('key_press_event', press)
        mid = connect('motion_notify_event', move)
    except:
        pass

def openout():
    global outf, x0, y0, x1, y1, xlog, ylog
    fn = inp[1].get()
    fn = fn.strip()
    print('Opening Outfile: %s'%fn)
    try:
        outf = open(fn, 'w')
    except:
        print('cannot open file %s'%fn)
        return
    
    b = inp[2].get()
    b = b.split(',')
    x0 = float(b[0])
    x1 = float(b[1])
    if len(b) == 3:
        xlog = int(b[2])
    else:
        xlog = 0
    b = inp[3].get()
    b = b.split(',')
    y0 = float(b[0])
    y1 = float(b[1])
    if len(b) == 3:
        ylog = int(b[2])
    else:
        ylog = 0
    print('xd0,xd1,xlog = %10.3E,%10.3E,%d'%(x0, x1, xlog))
    print('yd0,yd1,ylog = %10.3E,%10.3E,%d'%(y0, y1, ylog))
    if xlog:
        x0 = log10(x0)
        x1 = log10(x1)
    if ylog:
        y0 = log10(y0)
        y1 = log10(y1)
        
def closeout():
    global outf
    fn = inp[1].get()
    fn = fn.strip()
    print('Closing Outfile: %s'%fn)
    try:
        outf.close()
    except:
        pass
        
def quit():
    global root
    closeout()
    root.quit()
       
def move(event):
    global ax, ay, bx, by, x0, y0, x1, y1, i0, i1, j0, j1, outf, inp
        
    if (event.key == 'm' or event.key == 'M'):
        x = ax*event.xdata + bx
        y = ay*event.ydata + by
        if xlog:
            x = 10**x
        if ylog:
            y = 10**y
        print('%12.5E %12.5E %12.5E %12.5E'%(event.xdata, event.ydata, x, y))
        outf.write("%12.5E %12.5E\n"%(x, y))
        
def press(event):
    global ax, ay, bx, by, x0, y0, x1, y1, i0, i1, j0, j1, outf, inp, xlog, ylog

    if (outf == None):
        openout()
    if (outf.closed):
        openout()
    
    if event.key == 'a' or event.key == 'A':
        i0 = event.xdata
        j0 = event.ydata
        ax = None
        print('x0=%12.5E, y0=%12.5E'%(i0, j0))
    elif event.key == 'b' or event.key == 'B':
        if (i0 == None):
            print('define x0, y0 with left button while pressing "a"')
            return
        i1 = event.xdata
        j1 = event.ydata
        print('x1=%12.5E, y1=%12.5E'%(i1, j1))
        ax = (x1 - x0)/(i1 - i0)
        bx = x0 - ax*i0
        ay = (y1 - y0)/(j1 - j0)
        by = y0 - ay*j0
        print('ax, bx = %f, %f'%(ax, bx))
        print('ay, by = %f, %f'%(ay, by))
    elif event.key == 'd' or event.key == 'D':
        if (ax == None):
            print('define x0, y0 with left button while pressing "a"')
            print('define x1, y1 with left button while pressing "b"')
            return
        x = ax*event.xdata + bx
        y = ay*event.ydata + by
        if xlog:
            x = 10**x
        if ylog:
            y = 10**y
        print('%12.5E %12.5E %12.5E %12.5E'%(event.xdata, event.ydata, x, y))
        outf.write("%12.5E %12.5E\n"%(x, y)) 
    elif event.key == 'q' or event.key == 'Q':
        closeout()
    elif event.key == 'e' or event.key == 'E':
        quit()
    
from Tkinter import *
root = Tk()
root.title('Data Extractor')
f = Frame(root)
f.pack()
inpn = ['Infile', 'Outfile', 'xlim', 'ylim']
fn0 = ''
fn1 = ''
xy0 = '0.0, 1.0'
xy1 = '0.0, 1.0'
try:
    fn0 = sys.argv[1]
    fn1 = sys.argv[2]
    xy0 = '%s, %s'%(sys.argv[3], sys.argv[4])
    xy1 = '%s, %s'%(sys.argv[5], sys.argv[6])
except:
    pass
inpv = [fn0, fn1, xy0, xy1]
inp = []
for i in range(len(inpn)):
    Label(f, text=inpn[i]).grid(row=i)
    inp.append(Entry(f, width=32))
    inp[-1].grid(row=i, column=1)
    inp[-1].delete(0, END)
    inp[-1].insert(END,inpv[i])
f = Frame(root)
f.pack()
Button(f, text='Plot', width=5, command=plotimage).pack(side=LEFT)
Button(f, text='Open', width=5, command=openout).pack(side=LEFT)
Button(f, text='Close', width=5, command=closeout).pack(side=LEFT)
Button(f, text='Quit', width=5, command=quit).pack(side=LEFT)
ion()
root.mainloop()
